"""empty message

Revision ID: 212f83b47768
Revises: 046b13874320
Create Date: 2017-02-01 22:30:23.355286

"""

# revision identifiers, used by Alembic.
revision = '212f83b47768'
down_revision = '046b13874320'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('billing_first_name', sa.String(), nullable=True),
    sa.Column('billing_last_name', sa.String(), nullable=True),
    sa.Column('billing_street', sa.String(), nullable=True),
    sa.Column('billing_city', sa.String(), nullable=True),
    sa.Column('billing_zip', sa.String(), nullable=True),
    sa.Column('billing_country', sa.String(), nullable=True),
    sa.Column('delivery_first_name', sa.String(), nullable=True),
    sa.Column('delivery_last_name', sa.String(), nullable=True),
    sa.Column('delivery_street', sa.String(), nullable=True),
    sa.Column('delivery_city', sa.String(), nullable=True),
    sa.Column('delivery_zip', sa.String(), nullable=True),
    sa.Column('delivery_country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase')
    # ### end Alembic commands ###
