"""empty message

Revision ID: 345b8b883807
Revises: dfbb066b534f
Create Date: 2016-12-08 19:05:55.152826

"""

# revision identifiers, used by Alembic.
revision = '345b8b883807'
down_revision = 'dfbb066b534f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('article_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'photos', 'press', ['article_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'article_id')
    # ### end Alembic commands ###
