"""empty message

Revision ID: 5af141f4bde9
Revises: c5bbc90a1a64
Create Date: 2017-01-04 23:00:28.020196

"""

# revision identifiers, used by Alembic.
revision = '5af141f4bde9'
down_revision = 'c5bbc90a1a64'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_item_photo', sa.Column('is_thumbnail', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_item_photo', 'is_thumbnail')
    # ### end Alembic commands ###
