"""empty message

Revision ID: 633b8f93d3d7
Revises: ae68a3181ca3
Create Date: 2017-01-02 15:55:55.592693

"""

# revision identifiers, used by Alembic.
revision = '633b8f93d3d7'
down_revision = 'ae68a3181ca3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('press_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['press.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('photos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], [u'press.id'], name=u'photos_article_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'photos_pkey')
    )
    op.drop_table('press_photos')
    # ### end Alembic commands ###
