"""empty message

Revision ID: 70f2243cdf61
Revises: c72908188c20
Create Date: 2017-01-05 11:01:32.618665

"""

# revision identifiers, used by Alembic.
revision = '70f2243cdf61'
down_revision = 'c72908188c20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('press',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('tag_line', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=19, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('dna', sa.String(), nullable=True),
    sa.Column('care', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('press_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('press_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.ForeignKeyConstraint(['press_id'], ['press.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_item_colour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_item_id', sa.Integer(), nullable=False),
    sa.Column('colour_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colour_id'], ['colour.id'], ),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_item_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_item_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('is_thumbnail', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_item_size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_item_id', sa.Integer(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_item.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['size.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_item_size')
    op.drop_table('shop_item_photo')
    op.drop_table('shop_item_colour')
    op.drop_table('press_photos')
    op.drop_table('size')
    op.drop_table('shop_item')
    op.drop_table('press')
    op.drop_table('photo')
    op.drop_table('colour')
    # ### end Alembic commands ###
