"""empty message

Revision ID: 909cc87288b4
Revises: 633b8f93d3d7
Create Date: 2017-01-03 22:16:39.113566

"""

# revision identifiers, used by Alembic.
revision = '909cc87288b4'
down_revision = '633b8f93d3d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('dna', sa.String(), nullable=True),
    sa.Column('care', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_item_colour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_item_id', sa.Integer(), nullable=False),
    sa.Column('colour_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colour_id'], ['colour.id'], ),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_item_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_item_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_item_size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_item_id', sa.Integer(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_item.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['size.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_item_size')
    op.drop_table('shop_item_photo')
    op.drop_table('shop_item_colour')
    op.drop_table('size')
    op.drop_table('shop_item')
    op.drop_table('colour')
    # ### end Alembic commands ###
