"""empty message

Revision ID: 9f80e6a4c675
Revises: 909cc87288b4
Create Date: 2017-01-04 15:01:01.383841

"""

# revision identifiers, used by Alembic.
revision = '9f80e6a4c675'
down_revision = '909cc87288b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'press_photos', sa.Column('photo_id', sa.Integer(), nullable=False))
    op.add_column(u'press_photos', sa.Column('press_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'press_photos_article_id_fkey', 'press_photos', type_='foreignkey')
    op.create_foreign_key(None, 'press_photos', 'press', ['press_id'], ['id'])
    op.create_foreign_key(None, 'press_photos', 'photo', ['photo_id'], ['id'])
    op.drop_column(u'press_photos', 'url')
    op.drop_column(u'press_photos', 'article_id')
    op.add_column(u'shop_item_photo', sa.Column('photo_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'shop_item_photo', 'photo', ['photo_id'], ['id'])
    op.drop_column(u'shop_item_photo', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'shop_item_photo', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shop_item_photo', type_='foreignkey')
    op.drop_column(u'shop_item_photo', 'photo_id')
    op.add_column(u'press_photos', sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column(u'press_photos', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'press_photos', type_='foreignkey')
    op.drop_constraint(None, 'press_photos', type_='foreignkey')
    op.create_foreign_key(u'press_photos_article_id_fkey', 'press_photos', 'press', ['article_id'], ['id'])
    op.drop_column(u'press_photos', 'press_id')
    op.drop_column(u'press_photos', 'photo_id')
    op.drop_table('photo')
    # ### end Alembic commands ###
