"""empty message

Revision ID: ae68a3181ca3
Revises: 345b8b883807
Create Date: 2017-01-02 15:55:04.336408

"""

# revision identifiers, used by Alembic.
revision = 'ae68a3181ca3'
down_revision = '345b8b883807'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('press', sa.Column('published', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('press', 'published')
    # ### end Alembic commands ###
