"""empty message

Revision ID: c72908188c20
Revises: 5af141f4bde9
Create Date: 2017-01-05 11:00:58.561357

"""

# revision identifiers, used by Alembic.
revision = 'c72908188c20'
down_revision = '5af141f4bde9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_item', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('shop_item', sa.Column('price', sa.Numeric(precision=19, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_item', 'price')
    op.drop_column('shop_item', 'currency')
    # ### end Alembic commands ###
